export const ICE_BREAKERS = [
  "What do you build at work?",
  "What are you learning lately?",
  "What’s your tech stack?",
  "What are you building for fun?",
  "What’s one tool you love?",
  "What tool should I try?",
  "What’s your favorite shortcut?",
  "What’s your go-to editor/IDE?",
  "Dark mode or light mode?",
  "Tabs or spaces?",
  "Mac, Windows, or Linux?",
  "Frontend, backend, or both?",
  "What’s your current project?",
  "What’s your next project idea?",
  "What’s a tiny win this week?",
  "What problem are you solving?",
  "What’s a good resource you found?",
  "Any podcast/newsletter you like?",
  "What’s a library you recommend?",
  "What’s your favorite API?",
  "What’s your usual debugging move?",
  "Best “aha!” moment recently?",
  "What’s something you automated?",
  "What’s your best dev habit?",
  "What’s one habit you want?",
  "What do you want to get better at?",
  "What’s your role right now?",
  "What’s your dream role?",
  "What brought you here today?",
  "What’s one thing you want help with?",
  "Want to swap GitHub/LinkedIn?",
  "What meetup would you love next?",
  "If you had 1 free hour, what would you code?",
  "What’s your favorite “small” project?",
  "What’s one tip for new devs?",
];
